# Welcome to Elytra 2.x.x config !
# Here configure which block are considered "bouncable", enter their ids. 
# Try going on those blocks by using the elytra and the see the magic.
bouncable_blocks: [165, 88]