BlocksPerTick: 256
blocks:
  "3:2": "243:0"
  "31:1": "2:0"
  "43:7": "43:6"
  "44:7": "44:6"
  "82:0": "337:0"
  "112:0": "405:0"
  "115:0": "372:0"
  "157:0": "126:0"
  "158:0": "125:0"
  "188:0": "85:1"
  "189:0": "85:2"
  "190:0": "85:3"
  "191:0": "85:5"
  "192:0": "85:4"
  "198:0": "208:0"
  "199:0": "240:0"
  "202:0": "201:2"
  "205:0": "44:7"
  "207:0": "244:0"
  "208:0": "198:0"
  "214:0": "115:0"
  "322:1": "466:0"
  "410:0": "422:0"
  "434:0": "457:0"
  "435:0": "458:0"
  "436:0": "459:0"
  "450:0": "445:0"
