BlocksPerTick: 256
blocks:
    "243:0": "3:2"
    "2:0": "31:1"
    "43:6": "43:7"
    "44:6": "44:7"
    "337:0": "82:0"
    "405:0": "112:0"
    "372:0": "115:0"
    "126:0": "158:0"
    "126:1": "158:1"
    "126:8": "158:8"
    "125:0": "157:0"
    "85:1": "188:0"
    "85:2": "189:0"
    "85:3": "190:0"
    "85:5": "191:0"
    "85:4": "192:0"
    "208:0": "198:0"
    "240:0": "199:0"
    "201:2": "202:0"
    "44:7": "205:0"
    "244:0": "207:0"
    "198:0": "208:0"
    "115:0": "214:0"
    "466:0": "322:1"
    "422:0": "410:0"
    "457:0": "434:0"
    "458:0": "435:0"
    "459:0": "436:0"
    "445:0": "450:0"
    "143:1": "143:5"
    "77:1": "77:5"
    "77:4": "77:2"
    "96:4": "96:15"
    "96:5": "96:14"
    "96:6": "96:13"
    "96:7": "96:12"